#!/bin/bash

clear
#-- colors --#
#R='\e[1;31m' #RED
#G='\e[1;32m' #GREEN
#B='\e[1;34m' #BLUE
#Y='\e[1;33m' #YELLOW
#C='\e[1;36m' #CYAN
W='\e[1;37m' #WHITE
##############

#-- colors v2 --#
R='\e[31;1m' #RED
G='\e[32;1m' #GREEN
Y='\e[33;1m' #YELLOW
DB='\e[34;1m' #DARKBLUE
P='\e[35;1m' #PURPLE
LB='\e[36;1m' #LIGHTBLUE

#-- colors v3 --#
BR='\e[3;31m' #RED
BG='\e[3;32m' #GREEN
BY='\e[3;33m' #YELLOW
BDB='\e[3;34m' #DARKBLUE
BP='\e[3;35m' #PURPLE
BLB='\e[3;36m' #LIGHTBLUE

echo -e "$Y"
xderm-mini(){
read -p "akan menginstall xderm-mini,apakah anda yakin? (y/n) : " an
if [[ $an == "y" || $an == "Y" ]]; then
echo -e "memulai penginstallan xderm-mini"
sleep 2
clear
wget --no-check-certificate "https://raw.githubusercontent.com/vitoharhari/xderm-mini/main/install-xderm-mini" -P /usr/bin/ && chmod 777 /usr/bin/install-xderm-mini && bash install-xderm-mini
sleep 2
else
clear
echo -e "kembali ke halaman awal..."
sleep 2
clear
exit
fi
}
echo -e ""
xderm-mini-gui(){
read -p "akan menginstall xderm-mini-gui,pastikan xderm-mini sudah terinstall. apakah anda yakin? (y/n) : " an
if [[ $an == "y" || $an == "Y" ]]; then
echo -e "memulai penginstallan xderm-mini-gui"
sleep 2
clear
wget --no-check-certificate "https://raw.githubusercontent.com/ryanfauzi1/xderm-mini_GUI/main/installer" -O /root/installer && chmod +x installer && bash installer
sleep 2
else
clear
echo -e "kembali ke halaman awal..."
sleep 2
clear
exit
fi
}
echo -e "$Y"
fix-xderm-mini-gui(){
read -p "akan memperbaiki xderm-mini-gui,apakah anda yakin? (y/n) : " an
if [[ $an == "y" || $an == "Y" ]]; then
echo -e "memulai perbaikan xderm-mini-gui"
sleep 2
clear
wget --no-check-certificate "https://raw.githubusercontent.com/vitoharhari/xderm-mini-gui/main/fix-xderm-mini-gui" -P /root/ && chmod 777 /root/fix-xderm-mini-gui && bash fix-xderm-mini-gui
sleep 2
else
clear
echo -e "kembali ke halaman awal..."
sleep 2
clear
exit
fi
}
echo -e "$Y"
install-login-page(){
read -p "akan menginstall login page xderm-mini-gui,apakah anda yakin? (y/n) : " an
if [[ $an == "y" || $an == "Y" ]]; then
echo -e "memulai penginstallan login page xderm-mini-gui"
sleep 2
clear
wget --no-check-certificate "https://raw.githubusercontent.com/vitoharhari/xderm-mini-gui/main/install-login-page" -P /root/ && chmod 777 /root/install-login-page && bash install-login-page
sleep 2
else
clear
echo -e "kembali ke halaman awal..."
sleep 2
clear
exit
fi
}
echo -e "$Y"
remove-login-page(){
read -p "akan menghapus login page xderm-mini-gui,apakah anda yakin? (y/n) : " an
if [[ $an == "y" || $an == "Y" ]]; then
echo -e "memulai penghapusan login page xderm-mini-gui"
sleep 2
clear
wget --no-check-certificate "https://raw.githubusercontent.com/vitoharhari/xderm-mini-gui/main/remove-login-page" -P /root/ && chmod 777 /root/remove-login-page && bash remove-login-page
sleep 2
else
clear
echo -e "kembali ke halaman awal..."
sleep 2
clear
exit
fi
}
echo -e "$Y"
speedtest(){
read -p "akan menginstall speedtest,apakah anda yakin? (y/n) : " an
if [[ $an == "y" || $an == "Y" ]]; then
echo -e "memulai penginstallan speedtest"
sleep 2
clear
wget --no-check-certificate "https://raw.githubusercontent.com/vitoharhari/speedtest/main/install-speedtest" -P /root/ && chmod 777 /root/install-speedtest && bash install-speedtest
sleep 2
else
clear
echo -e "kembali ke halaman awal..."
sleep 2
clear
exit
fi
}
echo -e "$Y"
install-terminal-luci(){
read -p "akan menginstall terminal-luci untuk openwrt v19,apakah anda yakin? (y/n) : " an
if [[ $an == "y" || $an == "Y" ]]; then
echo -e "memulai penginstallan terminal-luci"
sleep 2
clear
wget --no-check-certificate "https://raw.githubusercontent.com/vitoharhari/terminal-luci/main/install-terminal-luci" -P /root/ && chmod 777 /root/install-terminal-luci && bash install-terminal-luci
sleep 2
else
clear
echo -e "kembali ke halaman awal..."
sleep 2
clear
exit
fi
}
echo -e "$Y"
uninstall-terminal-luci(){
read -p "akan uninstall terminal-luci untuk openwrt v19,apakah anda yakin? (y/n) : " an
if [[ $an == "y" || $an == "Y" ]]; then
echo -e "memulai uninstall terminal-luci"
sleep 2
clear
wget --no-check-certificate "https://raw.githubusercontent.com/vitoharhari/terminal-luci/main/uninstall-terminal-luci" -P /root/ && chmod 777 /root/uninstall-terminal-luci && bash uninstall-terminal-luci
sleep 2
else
clear
echo -e "kembali ke halaman awal..."
sleep 2
clear
exit
fi
}
echo -e "$Y"
install-argonv19(){
read -p "akan menginstall argon untuk openwrt v19,apakah anda yakin? (y/n) : " an
if [[ $an == "y" || $an == "Y" ]]; then
echo -e "memulai penginstallan argon teme openwrt v19"
sleep 2
clear
wget --no-check-certificate "https://raw.githubusercontent.com/vitoharhari/argon-themev19/main/install-argon-v19" -P /root/ && chmod 777 /root/install-argon-v19 && bash install-argon-v19
sleep 2
else
clear
echo -e "kembali ke halaman awal..."
sleep 2
clear
exit
fi
}
echo -e "$Y"
uninstall-argonv19(){
read -p "akan uninstall argon untuk openwrt v19,apakah anda yakin? (y/n) : " an
if [[ $an == "y" || $an == "Y" ]]; then
echo -e "memulai uninstall argon teme openwrt v19"
sleep 2
clear
wget --no-check-certificate "https://raw.githubusercontent.com/vitoharhari/argon-themev19/main/uninstall-argon-v19" -P /root/ && chmod 777 /root/uninstall-argon-v19 && bash uninstall-argon-v19
sleep 2
else
clear
echo -e "kembali ke halaman awal..."
sleep 2
clear
exit
fi
}
echo -e "$Y"
install-argonv18(){
read -p "akan menginstall argon untuk openwrt v18,apakah anda yakin? (y/n) : " an
if [[ $an == "y" || $an == "Y" ]]; then
echo -e "memulai penginstallan argon teme openwrt v18"
sleep 2
clear
wget --no-check-certificate "https://raw.githubusercontent.com/vitoharhari/argon-themev18/main/install-argon-v18" -P /root/ && chmod 777 /root/install-argon-v18 && bash install-argon-v18
sleep 2
else
clear
echo -e "kembali ke halaman awal..."
sleep 2
clear
exit
fi
}
echo -e "$Y"
uninstall-argonv18(){
read -p "akan uninstall argon untuk openwrt v18,apakah anda yakin? (y/n) : " an
if [[ $an == "y" || $an == "Y" ]]; then
echo -e "memulai uninstall argon teme openwrt v18"
sleep 2
clear
wget --no-check-certificate "https://raw.githubusercontent.com/vitoharhari/argon-themev18/main/uninstall-argon-v18" -P /root/ && chmod 777 /root/uninstall-argon-v18 && bash uninstall-argon-v18
sleep 2
else
clear
echo -e "kembali ke halaman awal..."
sleep 2
clear
exit
fi
}
echo -e "$Y"
update-ain(){
rm -rf /usr/bin/update-ain &> /dev/null
echo -e " mengecek versi AIN"; wget --no-check-certificate "https://raw.githubusercontent.com/vitoharhari/ain/main/update-ain" -P /usr/bin &> /dev/null
sleep 1
an=$(cat /usr/bin/update-ain)
if [[ $an == *"1.2"* ]]; then
echo -e " AIN sudah$R versi terbaru"
rm -rf /usr/bin/update-ain &> /dev/null
echo -e "$Y"
sleep 2
ain
exit
else
echo -e "$P sedang memperbaharui..."
sleep 1
fi
rm -rf /usr/bin/update-ain &> /dev/null
an=$(find /usr/bin)
if [[ $an ==  *"ain"* ]]; then
rm -rf /usr/bin/ain &> /dev/null
echo -e "$G memperbaharui..."; wget --no-check-certificate "https://raw.githubusercontent.com/vitoharhari/ain/main/ain" -P /usr/bin &> /dev/null
sleep 1
chmod 777 /usr/bin/ain &> /dev/null
echo -e "$LB update selesai"
sleep 2
echo -e ""
else
echo -e "$G memperbaharui..."; wget --no-check-certificate "https://raw.githubusercontent.com/vitoharhari/ain/main/ain" -P /usr/bin &> /dev/null
sleep 1
chmod 777 /usr/bin/ain &> /dev/null
echo -e "$LB update selesai"
sleep 1
fi
}

banner(){
clear
echo -e "$DB ******************************************************"
echo -e "$DB ******************************************************"
echo -e " **                                                  **"
echo -e "$DB **$R      SELAMAT DATANG DI AIN (AUTO INSTALLER)      $DB**"
echo -e " **                                                  **"
echo -e "$DB ******************************************************"
echo -e "$DB **$Y       PILIH TOOLS YANG AKAN DI INSTALL!!!        $DB**"
echo -e "$DB ******************************************************"
echo -e "$DB **$G        DAFTAR :                    *  PERINTAH : $DB**"
echo -e "$DB **$G INSTALL XDERM-MINI                 *    ain 1    $DB**"
echo -e "$DB **$G INSTALL XDERM-MINI-GUI             *    ain 2    $DB**"
echo -e "$DB **$G FIX DOWNLOAD PHP XDERM-MINI-GUI    *    ain 3    $DB**"
echo -e "$DB **$G INSTALL LOGIN XDERM-MINI-GUI       *    ain 4    $DB**"
echo -e "$DB **$G REMOVE LOGIN XDERM-MINI-GUI        *    ain 5    $DB**"
echo -e "$DB **$G INSTALL SPEEDTEST BY OOKLA         *    ain 6    $DB**"
echo -e "$DB **$G INSTALL TERMINAL-LUCI V19          *    ain 7    $DB**"
echo -e "$DB **$G UNINSTALL TERMINAL-LUCI V19        *    ain 8    $DB**"
echo -e "$DB **$G INSTALL ARGON THEME V19            *    ain 9    $DB**"
echo -e "$DB **$G UNINSTALL ARGON THEME V19          *    ain 10   $DB**"
echo -e "$DB **$G INSTALL ARGON THEME V18            *    ain 11   $DB**"
echo -e "$DB **$G UNINSTALL ARGON THEME V18          *    ain 12   $DB**"
echo -e "$DB **$G UPDATE AIN KE VERSI TERBARU        *    ain 13   $DB**"
echo -e "$DB ******************************************************"
echo -e "$DB **$Y         AIN V1.2$DB *$Y COPYRIGHT$R @$Y VITO H.S          $DB**"
echo -e "$DB ******************************************************"
echo -e "$DB ******************************************************"
echo -e "$Y"
}

perubahan(){
wget --no-check-certificate "https://raw.githubusercontent.com/vitoharhari/ain/main/changelog-ain" -P /root/ -q
chmod 777 /root/changelog-ain
bash /root/changelog-ain
rm -rf /root/changelog-ain
}

case $1 in
"1")
xderm-mini;exit
;;
esac

case $1 in
"2")
xderm-mini-gui;exit
;;
esac

case $1 in
"3")
fix-xderm-mini-gui;exit
;;
esac

case $1 in
"4")
install-login-page;exit
;;
esac

case $1 in
"5")
remove-login-page;exit
;;
esac

case $1 in
"6")
speedtest;exit
;;
esac

case $1 in
"7")
install-terminal-luci;exit
;;
esac

case $1 in
"8")
uninstall-terminal-luci;exit
;;
esac

case $1 in
"9")
install-argonv19;exit
;;
esac

case $1 in
"10")
uninstall-argonv19;exit
;;
esac

case $1 in
"11")
install-argonv18;exit
;;
esac

case $1 in
"12")
uninstall-argonv18;exit
;;
esac

case $1 in
"13")
update-ain;perubahan;exit
;;
esac



clear
echo -e "$DB ******************************************************"
echo -e "$DB ******************************************************"
echo -e " **                                                  **"
echo -e "$DB **$R      SELAMAT DATANG DI AIN (AUTO INSTALLER)      $DB**"
echo -e " **                                                  **"
echo -e "$DB ******************************************************"
echo -e "$DB **$Y       PILIH TOOLS YANG AKAN DI INSTALL!!!        $DB**"
echo -e "$DB ******************************************************"
echo -e "$DB **$G        DAFTAR :                    *  PERINTAH : $DB**"
echo -e "$DB **$G INSTALL XDERM-MINI                 *    ain 1    $DB**"
echo -e "$DB **$G INSTALL XDERM-MINI-GUI             *    ain 2    $DB**"
echo -e "$DB **$G FIX DOWNLOAD PHP XDERM-MINI-GUI    *    ain 3    $DB**"
echo -e "$DB **$G INSTALL LOGIN XDERM-MINI-GUI       *    ain 4    $DB**"
echo -e "$DB **$G REMOVE LOGIN XDERM-MINI-GUI        *    ain 5    $DB**"
echo -e "$DB **$G INSTALL SPEEDTEST BY OOKLA         *    ain 6    $DB**"
echo -e "$DB **$G INSTALL TERMINAL-LUCI V19          *    ain 7    $DB**"
echo -e "$DB **$G UNINSTALL TERMINAL-LUCI V19        *    ain 8    $DB**"
echo -e "$DB **$G INSTALL ARGON THEME V19            *    ain 9    $DB**"
echo -e "$DB **$G UNINSTALL ARGON THEME V19          *    ain 10   $DB**"
echo -e "$DB **$G INSTALL ARGON THEME V18            *    ain 11   $DB**"
echo -e "$DB **$G UNINSTALL ARGON THEME V18          *    ain 12   $DB**"
echo -e "$DB **$G UPDATE AIN KE VERSI TERBARU        *    ain 13   $DB**"
echo -e "$DB ******************************************************"
echo -e "$DB **$Y         AIN V1.2$DB *$Y COPYRIGHT$R @$Y VITO H.S          $DB**"
echo -e "$DB ******************************************************"
echo -e "$DB ******************************************************"
echo -e "$Y"
exit
