#!/bin/bash

#-- colors --#
#R='\e[1;31m' #RED
#G='\e[1;32m' #GREEN
#B='\e[1;34m' #BLUE
#Y='\e[1;33m' #YELLOW
#C='\e[1;36m' #CYAN
W='\e[1;37m' #WHITE
##############

#-- colors v2 --#
R='\e[31;1m' #RED
G='\e[32;1m' #GREEN
Y='\e[33;1m' #YELLOW
DB='\e[34;1m' #DARKBLUE
P='\e[35;1m' #PURPLE
LB='\e[36;1m' #LIGHTBLUE

#-- colors v3 --#
BR='\e[3;31m' #RED
BG='\e[3;32m' #GREEN
BY='\e[3;33m' #YELLOW
BDB='\e[3;34m' #DARKBLUE
BP='\e[3;35m' #PURPLE
BLB='\e[3;36m' #LIGHTBLUE

echo -e "$Y"
echo -e " **********************************************"
echo -e "$Y *                                           $Y *"
echo -e "$Y *$G              changelog V1.2               $Y *"
echo -e "$Y *                                           $Y *"
echo -e " **********************************************"
echo -e "$Y *                                           $Y *"
echo -e "$Y *$R -added fix Download php xderm-mini-gui    $Y *"
echo -e "$Y *$R -added installer login page xderm-mini-gui$Y *"
echo -e "$Y *$R -added remover login page xderm-mini-gui  $Y *"
echo -e "$Y *                                           $Y *"
echo -e " **********************************************"
echo -e "$Y"
