#!/bin/bash

#-- colors v2 --#
R='\e[31;1m' #RED
G='\e[32;1m' #GREEN
Y='\e[33;1m' #YELLOW
DB='\e[34;1m' #DARKBLUE
P='\e[35;1m' #PURPLE
LB='\e[36;1m' #LIGHTBLUE

#-- colors v3 --#
BR='\e[3;31m' #RED
BG='\e[3;32m' #GREEN
BY='\e[3;33m' #YELLOW
BDB='\e[3;34m' #DARKBLUE
BP='\e[3;35m' #PURPLE
BLB='\e[3;36m' #LIGHTBLUE

clear
echo -e "$DB ************************************************"
echo -e "$DB *$G              auto installer AIN              $DB*"
echo -e "$DB ************************************************"
echo -e ""
echo -e "$Y menginstall AIN..."
sleep 2
an=$(find /usr/bin)
if [[ $an ==  *"ain"* ]]; then
rm -rf /usr/bin/ain
wget --no-check-certificate "https://raw.githubusercontent.com/vitoharhari/ain/main/ain" -P /usr/bin &> /dev/null
chmod 777 /usr/bin/ain &> /dev/null
else
wget --no-check-certificate "https://raw.githubusercontent.com/vitoharhari/ain/main/ain" -P /usr/bin &> /dev/null
chmod 777 /usr/bin/ain &> /dev/null
fi
sleep 2
echo -e "$LB AIN berhasil di install"
sleep 2
echo -e "$R ketik ain pada terminal untuk menjalankan tools AIN"
sleep 2
echo -e "$Y terima kasih dan sampai jumpa di auto installer selanjutnya"
sleep 2
ain 10
rm -rf /root/install-ain
